import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';

const APP_ID = process.env.GITHUB_APP_ID;
const PRIVATE_KEY = process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n');

if (!APP_ID || !PRIVATE_KEY) {
  console.warn('Missing GitHub App environment variables');
}

// Get Octokit instance for a specific installation
export function getOctokitForInstallation(installationId) {
  return new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: APP_ID,
      privateKey: PRIVATE_KEY,
      installationId: installationId,
    },
  });
}

// Get Octokit instance using user's access token
export function getOctokitForUser(accessToken) {
  return new Octokit({
    auth: accessToken,
  });
}

// Placeholder AI function - replace with actual AI integration
export async function generateDiff(prompt, fileContent) {
  // This is a placeholder - integrate with OpenAI/Claude/etc.
  const timestamp = new Date().toISOString();
  const addition = `\n\n## AI Generated Update\n\n**Prompt:** ${prompt}\n\n**Generated at:** ${timestamp}\n\nThis content was automatically generated by the PR Bot 🤖`;
  
  return fileContent + addition;
}
