// POST /api/create-pr - Create a PR with AI-generated content
import { createClient } from '@supabase/supabase-js';
import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

// Placeholder AI function - replace with actual AI integration
async function generateDiff(prompt, fileContent) {
  const timestamp = new Date().toISOString();
  const addition = `\n\n## AI Generated Update\n\n**Prompt:** ${prompt}\n\n**Generated at:** ${timestamp}\n\nThis content was automatically generated by the PR Bot 🤖`;
  return fileContent + addition;
}

// Process job in background
async function processJob(jobId) {
  try {
    // Get job details
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .select('*')
      .eq('id', jobId)
      .single();

    if (jobError || !job) {
      console.error('Job not found:', jobId);
      return;
    }

    // Update status to running
    await supabase
      .from('jobs')
      .update({ status: 'running' })
      .eq('id', jobId);

    // Get Octokit for this installation
    const octokit = new Octokit({
      authStrategy: createAppAuth,
      auth: {
        appId: process.env.GITHUB_APP_ID,
        privateKey: process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n'),
        installationId: job.installation_id,
      },
    });

    const owner = job.repo_owner;
    const repo = job.repo_name;

    // 1. Get default branch
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const baseBranch = repoData.default_branch;

    // 2. Get latest commit SHA (or handle empty repo)
    let baseSha;
    try {
      const { data: refData } = await octokit.git.getRef({
        owner,
        repo,
        ref: `heads/${baseBranch}`,
      });
      baseSha = refData.object.sha;
    } catch (error) {
      if (error.status === 409) {
        // Repository is empty, create initial commit
        const initialContent = `# ${repo}\n\nInitial commit by PR Bot 🤖`;
        const encoded = Buffer.from(initialContent).toString('base64');
        
        await octokit.repos.createOrUpdateFileContents({
          owner,
          repo,
          path: 'README.md',
          message: 'Initial commit',
          content: encoded,
          branch: baseBranch,
        });
        
        const { data: refData } = await octokit.git.getRef({
          owner,
          repo,
          ref: `heads/${baseBranch}`,
        });
        baseSha = refData.object.sha;
      } else {
        throw error;
      }
    }

    // 3. Create new branch
    const newBranch = `bot/ai-update-${Date.now()}`;

    await octokit.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${newBranch}`,
      sha: baseSha,
    });

    // 4. Get README (if exists)
    let content = '';
    let fileSha = null;
    try {
      const { data } = await octokit.repos.getContent({
        owner,
        repo,
        path: 'README.md',
        ref: newBranch,
      });
      content = Buffer.from(data.content, 'base64').toString('utf8');
      fileSha = data.sha;
    } catch (e) {
      content = `# ${repo}\n`;
    }

    // 5. Generate AI content
    const newContent = await generateDiff(job.prompt, content);

    // 6. Create/update README
    const encoded = Buffer.from(newContent).toString('base64');

    const updateParams = {
      owner,
      repo,
      path: 'README.md',
      message: `AI Update: ${job.prompt.substring(0, 50)}...`,
      content: encoded,
      branch: newBranch,
    };

    if (fileSha) {
      updateParams.sha = fileSha;
    }

    await octokit.repos.createOrUpdateFileContents(updateParams);

    // 7. Create PR
    const { data: pr } = await octokit.pulls.create({
      owner,
      repo,
      title: `AI Update: ${job.prompt.substring(0, 50)}...`,
      head: newBranch,
      base: baseBranch,
      body: `## AI-Generated Pull Request\n\n**Prompt:** ${job.prompt}\n\n---\n\n*This PR was created automatically by PR Bot*`,
    });

    // 8. Update job with success
    await supabase
      .from('jobs')
      .update({
        status: 'done',
        pr_url: pr.html_url,
      })
      .eq('id', jobId);

  } catch (error) {
    console.error('Job processing error:', error);
    
    // Update job with failure
    await supabase
      .from('jobs')
      .update({
        status: 'failed',
        error: error.message,
      })
      .eq('id', jobId);
  }
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const authHeader = req.headers.authorization;
  if (!authHeader?.startsWith('Bearer ')) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  const token = authHeader.substring(7);

  try {
    // Get session and user
    const { data: session, error: sessionError } = await supabase
      .from('sessions')
      .select('user_id')
      .eq('token', token)
      .gt('expires_at', new Date().toISOString())
      .single();

    if (sessionError || !session) {
      return res.status(401).json({ error: 'Invalid or expired session' });
    }

    // Get user's installation
    const { data: installation, error: installError } = await supabase
      .from('installations')
      .select('installation_id')
      .eq('user_id', session.user_id)
      .single();

    if (installError || !installation) {
      return res.status(400).json({ error: 'No GitHub App installation found' });
    }

    const { repo, prompt } = req.body;

    if (!repo || !prompt) {
      return res.status(400).json({ error: 'Missing repo or prompt' });
    }

    const [owner, repoName] = repo.split('/');

    // Create job
    const { data: job, error: jobError } = await supabase
      .from('jobs')
      .insert({
        user_id: session.user_id,
        installation_id: installation.installation_id,
        repo_owner: owner,
        repo_name: repoName,
        prompt: prompt,
        status: 'pending',
      })
      .select()
      .single();

    if (jobError) {
      console.error('Job creation error:', jobError);
      return res.status(500).json({ error: 'Failed to create job' });
    }

    // Process job asynchronously (in background)
    // Note: In Vercel, this will still run but response is sent immediately
    processJob(job.id).catch(console.error);

    res.json({ jobId: job.id });
  } catch (error) {
    console.error('Create PR error:', error);
    res.status(500).json({ error: 'Server error' });
  }
}
